{% set name = "saws" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f878a6996a7d6a9bf7a7617baa7ed1a1a9249f803cbc00874ad8c74ff82b639

build:
  number: 1
  entry_points:
    - saws = saws.main:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - awscli >=1.7.46,<2.0.0
    - click >=4.0,<7.0
    - configobj >=5.0.6,<6.0.0
    - pip
    - prompt-toolkit >=1.0.0,<1.1.0
    - pygments >=2.0.2,<3.0.0
    - python
    - six >=1.9.0,<2.0.0
  run:
    - awscli >=1.7.46,<2.0.0
    - click >=4.0,<7.0
    - configobj >=5.0.6,<6.0.0
    - prompt-toolkit >=1.0.0,<1.1.0
    - pygments >=2.0.2,<3.0.0
    - python
    - six >=1.9.0,<2.0.0

test:
  imports:
    - saws
    - saws.resource
    - scratch
    - scratch.option
    - tests
  commands:
    - saws --help

about:
  home: https://github.com/donnemartin/saws
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A Supercharged AWS CLI

  description: |
    SAWS improves the ease of use of the AWS CLI by autocompleting commands / subcommands / options, autocompleting resources (bucket names, instance ids, and instance tags), and more.
  doc_url: https://github.com/donnemartin/saws/tree/master/docs/source
  dev_url: https://github.com/donnemartin/saws
  home: https://github.com/donnemartin/saws

extra:
  recipe-maintainers:
    - agcopenhaver
