travis:
  secure:
    BINSTAR_TOKEN: KWJ+c1TCPViXHQukdfeMTtWGGqxUyEDB2ODxwoNwCt+IB0NM/YZ/NP1Db0mfvwuBU4waC41ige4hZNq6B+aYb1c3hRfPhfN+DzbxY1FBUvE/SxTEqTA9mo7+hcBGCmR0ApwgsJ615OsI/KxhO0Jmj9usEEJyMtxFslPaZ6nhtHxdJQDHCWRZdY5RKeRloOJp8FJXyIoYLh1ODusDr+PWqRD/N1OQ6+aXRyzi+F2L5kcPL410IP7j6ItgIwOQmh0Yf7Kpo07D3qr42H495tvSNN1wKIaS5i/+TWdfwrZQWj6yydRSVLNqKQ9FZS7FqKFszEVqPOdGFQozy0AX++64/HfwZ/4a8w9H1lvkfZ82OrKgkjlDxoRFjuD4fzsUSiKfy1rnmhRqjihJ0eMptJE2LN7zRs4lra16e+9RJ6szo/OUIwi30p1X37BK+cbCvSSFrtUszLQqNJWCf77vOGca51V4rFlWBB+IaOK59gWkcynC1qAOcaltlmdOaD2ad4Bm+w85BAirt2fTVvf00r6DGfiUUnT5rNmCC44zCGBQuKFL/v446AYe74s2dVALIPlU2P3iCHCgQvvDOKZ9R15YL//x7liU4zGZPawswhVrEuHACb90QZG/yqzebzWnGJnv9ojbGzo8AcCkvYGl03V5Nt6vGeapwnLWwum4jasYUZo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
